# Generated by Django 4.2.4 on 2023-10-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='prodents')),
                ('image2', models.ImageField(upload_to='prodents')),
                ('image3', models.ImageField(upload_to='prodents')),
                ('image4', models.ImageField(upload_to='prodents')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('stock', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_sid.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_sid.category')),
            ],
        ),
    ]
