# Generated by Django 4.2.4 on 2023-10-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodect',
            new_name='Product',
        ),
    ]
